title: Обучающий репозиторий
description: Материалы для изучения, выполнения работ по основным направлениям в разработке программного обеспечения в области автоматизации технологических процессов
author:
  name: Худайбирдин И.М.
  email: i-khudaibirdin@yandex.ru
remote_theme: "jekyll/minima@1e8a445"
permalink: pretty
baseurl: /university
minima:
  skin: classic
  social_links:
    - title: Github
      icon: github
      url: "https://github.com/khudaibirdin"
  hide_site_feed_link: true
  nav_pages:
    - about.md
markdown: kramdown
kramdown:
  input: GFM
